# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'NYCApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYCApp
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MaterialComponents/BottomNavigation'
  pod 'MaterialComponents/BottomNavigation+Theming'
end

